# safelist
branches:
  only:
  - master
  # - travis
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- git clone https://github.com/parsiya/parsiya.io parsiya.io
- cd parsiya.io
- git submodule init
- git submodule update --recursive --remote
script:
- hugo --minify
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: parsiya.io
  region: us-east-1
  local-dir: public
  skip_cleanup: true
  acl: public_read
  on:
    # Add other branches here.
    branch:
    - master